spring:
  datasource:
    url: jdbc:h2:mem:listings_service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  flyway:
    enabled: false

  devtools:
    restart:
      enabled: false

server:
  port: 8083

springdoc:
  swagger-ui:
    try-it-out-enabled: true
logging:
  level:
    com.motohive.listingservice: DEBUG